CREATE TABLE USR(
    id INT AUTO_INCREMENT  PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(100)  NOT NULL,
    active VARCHAR (5) NOT NULL
);

CREATE TABLE USER_ROLE(
    id INT AUTO_INCREMENT  PRIMARY KEY,
    ROLES VARCHAR(200) NOT NULL,
    USER_ID INT(1)  NOT NULL
);

INSERT INTO USR VALUES(1, 'admin', '$2a$08$0Rlpm1etqnpKlrk5Oaquj.8Alo.4P6M6E159byp4IN38xJ2Hc1pue', 'admin@admin.ru', 'TRUE');
INSERT INTO USR VALUES(2, 'user', '$2a$08$0Rlpm1etqnpKlrk5Oaquj.8Alo.4P6M6E159byp4IN38xJ2Hc1pue', 'user@user.ru', 'TRUE');
INSERT INTO USR VALUES(3, 'anotherUser', '$2a$08$0Rlpm1etqnpKlrk5Oaquj.8Alo.4P6M6E159byp4IN38xJ2Hc1pue', 'auser@auser.com', 'TRUE');

INSERT INTO USER_ROLE VALUES(1, 'USER', '1');
INSERT INTO USER_ROLE VALUES(2, 'ADMIN', '1');
INSERT INTO USER_ROLE VALUES(3, 'USER', '2');
INSERT INTO USER_ROLE VALUES(4, 'USER', '3');
